language: python
sudo: false
python:
 - "2.7"
 - "3.4"
env:
  global:
   - DRF="djangorestframework==3.2.3"
   - WQDB="https://github.com/wq/wq.db/archive/master.zip"
   - DRP="https://github.com/wq/django-rest-pandas/archive/master.zip"
  matrix:
   - DJANGO="django==1.7.10"
   - DJANGO="django==1.8.4"
   - DJANGO="django==1.8.4" LINT=1
before_script:
 - createdb -Upostgres vera_test
 - psql -Upostgres vera_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install $DRP
 - pip install $WQDB
 - pip install flake8
script:
 - ./runtests.sh
services:
 - redis-server
